// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUL_lEPL9M4It5sydvKF6H2B4D2OxCTNA',
    appId: '1:110041391170:android:aa6537edd36f22a10e8ddb',
    messagingSenderId: '110041391170',
    projectId: 'mini-shopping-cart-flutter',
    storageBucket: 'mini-shopping-cart-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_VQ6nMz7ZVJVugZTlfdK1E_z_1JYmPQ',
    appId: '1:110041391170:ios:352adef4386ff63b0e8ddb',
    messagingSenderId: '110041391170',
    projectId: 'mini-shopping-cart-flutter',
    storageBucket: 'mini-shopping-cart-flutter.firebasestorage.app',
    iosBundleId: 'com.example.miniShoppingCart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxR17FxKsriyX0oojPWUGi9XLAU0d2W0',
    appId: '1:110041391170:web:3fc20af8ba5742d20e8ddb',
    messagingSenderId: '110041391170',
    projectId: 'mini-shopping-cart-flutter',
    authDomain: 'mini-shopping-cart-flutter.firebaseapp.com',
    storageBucket: 'mini-shopping-cart-flutter.firebasestorage.app',
  );

}